cicd: swap out used sub-actions for setting up a nightly build

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -55,31 +55,44 @@ jobs:
         id: "build"
         uses: "./.github/actions/build"
 
-      - name: "Delete Nightly"
+      - name: Publish Nightly Release
+        id: create_release
         if: ${{ !inputs.release_name || inputs.release_name == 'nightly' }}
-        uses: sgpublic/delete-release-action@v1.1
-        with:
-          release-drop: false
-          draft-drop: false
-          pre-release-drop: true
-          pre-release-keep-count: -1
+        uses: viperproject/create-nightly-release@v1
         env:
           GITHUB_TOKEN: ${{ github.token }}
-
-      - name: "Publish Nightly Release"
-        if: ${{ inputs.release_name == 'nightly' }}
-        uses: ncipollo/release-action@v1
         with:
-          artifacts: "${{ github.workspace }}/build.zip"
-          name: 'FLUF Nightly Release'
+          tag_name: 'nightly-${{ needs.date-check.outputs.date }}'
+          release_name: Nightly Release
           body: 'This build is automatically generated from the latest commit every night (3 AM UTC). No build will be generated if no commit happens in a day.'
-          tag: 'nightly'
+          keep_num: 0
+          keep_tags: false
+
+      - name: Add build.zip to Nightly Release
+        uses: WebFreak001/deploy-nightly@v3.1.0
+        id: 'publish_nightly'
+        if: steps.create_release.outcome == 'success'
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          release_id: ${{ steps.create_release.outputs.id }}
+          asset_path: ./build.zip
+          asset_name: FLUF Nightly.zip
+          asset_content_type: application/zip
+          max_releases: 1
 
       - name: "Publish Named Release"
-        if: ${{ inputs.release_name != 'nightly' }}
+        id: 'publish_named'
+        if: ${{ inputs.release_name && inputs.release_name != 'nightly' }}
         uses: ncipollo/release-action@v1
         with:
           artifacts: "${{ github.workspace }}/build.zip"
           name: '${{ inputs.release_name }}'
           body: 'Changelog: https://github.com/TheStarport/FLUF/blob/master/CHANGELOG.md'
           tag: ${{ inputs.version != '' && inputs.version || needs.date-check.outputs.date }}
+
+      - name: "Validate Successful Publish"
+        if: ${{ !(steps.publish_named.outcome == 'success' || steps.publish_nightly.outcome == 'success') }}
+        shell: bash
+        run: |
+          echo "Neither publish step was successful, reporting error."
+          exit 1
